cmake_minimum_required(VERSION 3.22)
project(rsm_android)
set(CMAKE_CXX_STANDARD 20)
add_library(rsm_android SHARED rsm_jni.cpp ../../../../../src/core/instance.cpp ../../../../../src/core/data_model.cpp ../../../../../src/core/base_part.cpp)
target_include_directories(rsm_android PRIVATE ../../../../../src)
find_library(log-lib log)
target_link_libraries(rsm_android ${log-lib})
