#pragma once
#include "signal.h"
#include <atomic>
#include <cstdint>
#include <memory>
#include <string>
#include <unordered_map>
#include <variant>
#include <vector>
namespace rsm{using AttributeValue=std::variant<std::monostate,bool,double,std::string>;class Instance{public:explicit Instance(std::string="Instance");virtual~Instance();const std::string&Name()const noexcept{return name_;}const std::string&Id()const noexcept{return id_;}void SetId(std::string);void SetName(std::string);const std::string&ClassName()const noexcept{return className_;}Instance*Parent()const noexcept{return parent_;}bool Archivable()const noexcept{return archivable_;}void SetArchivable(bool)noexcept;void SetParent(Instance*);static Instance*SetParent(std::unique_ptr<Instance>,Instance*);Instance*FindFirstChild(const std::string&,bool=false)const;Instance*FindById(const std::string&)const;Instance*FindFirstChildOfClass(const std::string&)const;std::vector<Instance*>GetChildren()const;std::vector<Instance*>GetDescendants()const;void Destroy();virtual std::unique_ptr<Instance>Clone()const;void SetAttribute(std::string,AttributeValue);const AttributeValue*GetAttribute(const std::string&)const;const std::unordered_map<std::string,AttributeValue>&Attributes()const noexcept{return attributes_;}Signal<Instance*>ChildAdded,ChildRemoved;Signal<const std::string&>AttributeChanged,PropertyChanged;Signal<>Destroying;Signal<const std::string&>&GetPropertyChangedSignal(const std::string&){return PropertyChanged;}protected:void SetClassName(std::string c){className_=std::move(c);}void AddChild(std::unique_ptr<Instance>);void CopyStateTo(Instance&)const;void CloneChildrenTo(Instance&)const;private:static std::atomic<std::uint64_t>nextId_;std::string id_,name_="Instance",className_;Instance*parent_=nullptr;bool archivable_=true,destroyed_=false;std::vector<std::unique_ptr<Instance>>children_;std::unordered_map<std::string,AttributeValue>attributes_;friend class DataModel;};}